package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table balloon
 */
public class Balloon {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balloon.balloon_id
	 * @mbg.generated
	 */
	private Integer balloonId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balloon.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balloon.sid
	 * @mbg.generated
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balloon.cid
	 * @mbg.generated
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balloon.pid
	 * @mbg.generated
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column balloon.status
	 * @mbg.generated
	 */
	private Short status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balloon.balloon_id
	 * @return  the value of balloon.balloon_id
	 * @mbg.generated
	 */
	public Integer getBalloonId() {
		return balloonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balloon.balloon_id
	 * @param balloonId  the value for balloon.balloon_id
	 * @mbg.generated
	 */
	public void setBalloonId(Integer balloonId) {
		this.balloonId = balloonId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balloon.user_id
	 * @return  the value of balloon.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balloon.user_id
	 * @param userId  the value for balloon.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balloon.sid
	 * @return  the value of balloon.sid
	 * @mbg.generated
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balloon.sid
	 * @param sid  the value for balloon.sid
	 * @mbg.generated
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balloon.cid
	 * @return  the value of balloon.cid
	 * @mbg.generated
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balloon.cid
	 * @param cid  the value for balloon.cid
	 * @mbg.generated
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balloon.pid
	 * @return  the value of balloon.pid
	 * @mbg.generated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balloon.pid
	 * @param pid  the value for balloon.pid
	 * @mbg.generated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column balloon.status
	 * @return  the value of balloon.status
	 * @mbg.generated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column balloon.status
	 * @param status  the value for balloon.status
	 * @mbg.generated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}
}