package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blog
 */
public class Blog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.blog_id
	 * @mbg.generated
	 */
	private Integer blogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.language
	 * @mbg.generated
	 */
	private Integer language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.post_time
	 * @mbg.generated
	 */
	private Date postTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.nice
	 * @mbg.generated
	 */
	private Integer nice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.scan
	 * @mbg.generated
	 */
	private Integer scan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.blog_id
	 * @return  the value of blog.blog_id
	 * @mbg.generated
	 */
	public Integer getBlogId() {
		return blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.blog_id
	 * @param blogId  the value for blog.blog_id
	 * @mbg.generated
	 */
	public void setBlogId(Integer blogId) {
		this.blogId = blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.title
	 * @return  the value of blog.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.title
	 * @param title  the value for blog.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.language
	 * @return  the value of blog.language
	 * @mbg.generated
	 */
	public Integer getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.language
	 * @param language  the value for blog.language
	 * @mbg.generated
	 */
	public void setLanguage(Integer language) {
		this.language = language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.user_id
	 * @return  the value of blog.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.user_id
	 * @param userId  the value for blog.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.post_time
	 * @return  the value of blog.post_time
	 * @mbg.generated
	 */
	public Date getPostTime() {
		return postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.post_time
	 * @param postTime  the value for blog.post_time
	 * @mbg.generated
	 */
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.status
	 * @return  the value of blog.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.status
	 * @param status  the value for blog.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.nice
	 * @return  the value of blog.nice
	 * @mbg.generated
	 */
	public Integer getNice() {
		return nice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.nice
	 * @param nice  the value for blog.nice
	 * @mbg.generated
	 */
	public void setNice(Integer nice) {
		this.nice = nice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.scan
	 * @return  the value of blog.scan
	 * @mbg.generated
	 */
	public Integer getScan() {
		return scan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.scan
	 * @param scan  the value for blog.scan
	 * @mbg.generated
	 */
	public void setScan(Integer scan) {
		this.scan = scan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.content
	 * @return  the value of blog.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.content
	 * @param content  the value for blog.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}