package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table blog_discuss
 */
public class Blogdiscuss {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog_discuss.discuss_id
	 * @mbg.generated
	 */
	private Integer discussId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog_discuss.blog_id
	 * @mbg.generated
	 */
	private Integer blogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog_discuss.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog_discuss.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog_discuss.nice
	 * @mbg.generated
	 */
	private Integer nice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog_discuss.post_time
	 * @mbg.generated
	 */
	private Date postTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog_discuss.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog_discuss.discuss_id
	 * @return  the value of blog_discuss.discuss_id
	 * @mbg.generated
	 */
	public Integer getDiscussId() {
		return discussId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog_discuss.discuss_id
	 * @param discussId  the value for blog_discuss.discuss_id
	 * @mbg.generated
	 */
	public void setDiscussId(Integer discussId) {
		this.discussId = discussId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog_discuss.blog_id
	 * @return  the value of blog_discuss.blog_id
	 * @mbg.generated
	 */
	public Integer getBlogId() {
		return blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog_discuss.blog_id
	 * @param blogId  the value for blog_discuss.blog_id
	 * @mbg.generated
	 */
	public void setBlogId(Integer blogId) {
		this.blogId = blogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog_discuss.user_id
	 * @return  the value of blog_discuss.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog_discuss.user_id
	 * @param userId  the value for blog_discuss.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog_discuss.status
	 * @return  the value of blog_discuss.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog_discuss.status
	 * @param status  the value for blog_discuss.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog_discuss.nice
	 * @return  the value of blog_discuss.nice
	 * @mbg.generated
	 */
	public Integer getNice() {
		return nice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog_discuss.nice
	 * @param nice  the value for blog_discuss.nice
	 * @mbg.generated
	 */
	public void setNice(Integer nice) {
		this.nice = nice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog_discuss.post_time
	 * @return  the value of blog_discuss.post_time
	 * @mbg.generated
	 */
	public Date getPostTime() {
		return postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog_discuss.post_time
	 * @param postTime  the value for blog_discuss.post_time
	 * @mbg.generated
	 */
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog_discuss.content
	 * @return  the value of blog_discuss.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog_discuss.content
	 * @param content  the value for blog_discuss.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}