package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table category
 */
public class Category {

	/**
	 * Database Column Remarks: 主键 This field was generated by MyBatis Generator. This field corresponds to the database column category.category_id
	 * @mbg.generated
	 */
	private Integer categoryId;
	/**
	 * Database Column Remarks: 父分类id This field was generated by MyBatis Generator. This field corresponds to the database column category.pid
	 * @mbg.generated
	 */
	private Integer pid;
	/**
	 * Database Column Remarks: 科目名称 This field was generated by MyBatis Generator. This field corresponds to the database column category.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 描述 This field was generated by MyBatis Generator. This field corresponds to the database column category.desc
	 * @mbg.generated
	 */
	private String desc;
	/**
	 * Database Column Remarks: 九宫格背景图 This field was generated by MyBatis Generator. This field corresponds to the database column category.bg_url
	 * @mbg.generated
	 */
	private String bgUrl;
	/**
	 * Database Column Remarks: 九宫格logo This field was generated by MyBatis Generator. This field corresponds to the database column category.logo
	 * @mbg.generated
	 */
	private String logo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column category.post_time
	 * @mbg.generated
	 */
	private Date postTime;
	/**
	 * Database Column Remarks: 状态：1为正常，2为删除。 This field was generated by MyBatis Generator. This field corresponds to the database column category.status
	 * @mbg.generated
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.category_id
	 * @return  the value of category.category_id
	 * @mbg.generated
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.category_id
	 * @param categoryId  the value for category.category_id
	 * @mbg.generated
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.pid
	 * @return  the value of category.pid
	 * @mbg.generated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.pid
	 * @param pid  the value for category.pid
	 * @mbg.generated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.name
	 * @return  the value of category.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.name
	 * @param name  the value for category.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.desc
	 * @return  the value of category.desc
	 * @mbg.generated
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.desc
	 * @param desc  the value for category.desc
	 * @mbg.generated
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.bg_url
	 * @return  the value of category.bg_url
	 * @mbg.generated
	 */
	public String getBgUrl() {
		return bgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.bg_url
	 * @param bgUrl  the value for category.bg_url
	 * @mbg.generated
	 */
	public void setBgUrl(String bgUrl) {
		this.bgUrl = bgUrl == null ? null : bgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.logo
	 * @return  the value of category.logo
	 * @mbg.generated
	 */
	public String getLogo() {
		return logo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.logo
	 * @param logo  the value for category.logo
	 * @mbg.generated
	 */
	public void setLogo(String logo) {
		this.logo = logo == null ? null : logo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.user_id
	 * @return  the value of category.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.user_id
	 * @param userId  the value for category.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.post_time
	 * @return  the value of category.post_time
	 * @mbg.generated
	 */
	public Date getPostTime() {
		return postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.post_time
	 * @param postTime  the value for category.post_time
	 * @mbg.generated
	 */
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column category.status
	 * @return  the value of category.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column category.status
	 * @param status  the value for category.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}