package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table compileinfo
 */
public class Compileinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compileinfo.solution_id
	 * @mbg.generated
	 */
	private Integer solutionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column compileinfo.error
	 * @mbg.generated
	 */
	private String error;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compileinfo.solution_id
	 * @return  the value of compileinfo.solution_id
	 * @mbg.generated
	 */
	public Integer getSolutionId() {
		return solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compileinfo.solution_id
	 * @param solutionId  the value for compileinfo.solution_id
	 * @mbg.generated
	 */
	public void setSolutionId(Integer solutionId) {
		this.solutionId = solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column compileinfo.error
	 * @return  the value of compileinfo.error
	 * @mbg.generated
	 */
	public String getError() {
		return error;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column compileinfo.error
	 * @param error  the value for compileinfo.error
	 * @mbg.generated
	 */
	public void setError(String error) {
		this.error = error == null ? null : error.trim();
	}
}