package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table contest_problem
 */
public class Contestproblem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest_problem.problem_id
	 * @mbg.generated
	 */
	private Integer problemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest_problem.contest_id
	 * @mbg.generated
	 */
	private Integer contestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest_problem.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest_problem.num
	 * @mbg.generated
	 */
	private Integer num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest_problem.problem_id
	 * @return  the value of contest_problem.problem_id
	 * @mbg.generated
	 */
	public Integer getProblemId() {
		return problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest_problem.problem_id
	 * @param problemId  the value for contest_problem.problem_id
	 * @mbg.generated
	 */
	public void setProblemId(Integer problemId) {
		this.problemId = problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest_problem.contest_id
	 * @return  the value of contest_problem.contest_id
	 * @mbg.generated
	 */
	public Integer getContestId() {
		return contestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest_problem.contest_id
	 * @param contestId  the value for contest_problem.contest_id
	 * @mbg.generated
	 */
	public void setContestId(Integer contestId) {
		this.contestId = contestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest_problem.title
	 * @return  the value of contest_problem.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest_problem.title
	 * @param title  the value for contest_problem.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest_problem.num
	 * @return  the value of contest_problem.num
	 * @mbg.generated
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest_problem.num
	 * @param num  the value for contest_problem.num
	 * @mbg.generated
	 */
	public void setNum(Integer num) {
		this.num = num;
	}
}