package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table contest
 */
public class Contest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.contest_id
	 * @mbg.generated
	 */
	private Integer contestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.start_time
	 * @mbg.generated
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.end_time
	 * @mbg.generated
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.defunct
	 * @mbg.generated
	 */
	private String defunct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.is_private
	 * @mbg.generated
	 */
	private Byte isPrivate;
	/**
	 * Database Column Remarks: bits for LANG to mask This field was generated by MyBatis Generator. This field corresponds to the database column contest.langmask
	 * @mbg.generated
	 */
	private Integer langmask;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contest.description
	 * @mbg.generated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.contest_id
	 * @return  the value of contest.contest_id
	 * @mbg.generated
	 */
	public Integer getContestId() {
		return contestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.contest_id
	 * @param contestId  the value for contest.contest_id
	 * @mbg.generated
	 */
	public void setContestId(Integer contestId) {
		this.contestId = contestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.title
	 * @return  the value of contest.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.title
	 * @param title  the value for contest.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.start_time
	 * @return  the value of contest.start_time
	 * @mbg.generated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.start_time
	 * @param startTime  the value for contest.start_time
	 * @mbg.generated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.end_time
	 * @return  the value of contest.end_time
	 * @mbg.generated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.end_time
	 * @param endTime  the value for contest.end_time
	 * @mbg.generated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.defunct
	 * @return  the value of contest.defunct
	 * @mbg.generated
	 */
	public String getDefunct() {
		return defunct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.defunct
	 * @param defunct  the value for contest.defunct
	 * @mbg.generated
	 */
	public void setDefunct(String defunct) {
		this.defunct = defunct == null ? null : defunct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.is_private
	 * @return  the value of contest.is_private
	 * @mbg.generated
	 */
	public Byte getIsPrivate() {
		return isPrivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.is_private
	 * @param isPrivate  the value for contest.is_private
	 * @mbg.generated
	 */
	public void setIsPrivate(Byte isPrivate) {
		this.isPrivate = isPrivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.langmask
	 * @return  the value of contest.langmask
	 * @mbg.generated
	 */
	public Integer getLangmask() {
		return langmask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.langmask
	 * @param langmask  the value for contest.langmask
	 * @mbg.generated
	 */
	public void setLangmask(Integer langmask) {
		this.langmask = langmask;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.password
	 * @return  the value of contest.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.password
	 * @param password  the value for contest.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contest.description
	 * @return  the value of contest.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contest.description
	 * @param description  the value for contest.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}