package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table custominput
 */
public class Custominput {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custominput.solution_id
	 * @mbg.generated
	 */
	private Integer solutionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column custominput.input_text
	 * @mbg.generated
	 */
	private String inputText;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custominput.solution_id
	 * @return  the value of custominput.solution_id
	 * @mbg.generated
	 */
	public Integer getSolutionId() {
		return solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custominput.solution_id
	 * @param solutionId  the value for custominput.solution_id
	 * @mbg.generated
	 */
	public void setSolutionId(Integer solutionId) {
		this.solutionId = solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column custominput.input_text
	 * @return  the value of custominput.input_text
	 * @mbg.generated
	 */
	public String getInputText() {
		return inputText;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column custominput.input_text
	 * @param inputText  the value for custominput.input_text
	 * @mbg.generated
	 */
	public void setInputText(String inputText) {
		this.inputText = inputText == null ? null : inputText.trim();
	}
}