package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table db_info_inc
 */
public class Dbinfoinc {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_info_inc.var_key
	 * @mbg.generated
	 */
	private String varKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column db_info_inc.var_val
	 * @mbg.generated
	 */
	private Boolean varVal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column db_info_inc.var_key
	 * @return  the value of db_info_inc.var_key
	 * @mbg.generated
	 */
	public String getVarKey() {
		return varKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column db_info_inc.var_key
	 * @param varKey  the value for db_info_inc.var_key
	 * @mbg.generated
	 */
	public void setVarKey(String varKey) {
		this.varKey = varKey == null ? null : varKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column db_info_inc.var_val
	 * @return  the value of db_info_inc.var_val
	 * @mbg.generated
	 */
	public Boolean getVarVal() {
		return varVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column db_info_inc.var_val
	 * @param varVal  the value for db_info_inc.var_val
	 * @mbg.generated
	 */
	public void setVarVal(Boolean varVal) {
		this.varVal = varVal;
	}
}