package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table loginlog
 */
public class Loginlog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loginlog.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loginlog.password
	 * @mbg.generated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loginlog.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column loginlog.time
	 * @mbg.generated
	 */
	private Date time;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loginlog.user_id
	 * @return  the value of loginlog.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loginlog.user_id
	 * @param userId  the value for loginlog.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loginlog.password
	 * @return  the value of loginlog.password
	 * @mbg.generated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loginlog.password
	 * @param password  the value for loginlog.password
	 * @mbg.generated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loginlog.ip
	 * @return  the value of loginlog.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loginlog.ip
	 * @param ip  the value for loginlog.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column loginlog.time
	 * @return  the value of loginlog.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column loginlog.time
	 * @param time  the value for loginlog.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}
}