package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mail
 */
public class Mail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.mail_id
	 * @mbg.generated
	 */
	private Integer mailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.to_user
	 * @mbg.generated
	 */
	private String toUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.from_user
	 * @mbg.generated
	 */
	private String fromUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.new_mail
	 * @mbg.generated
	 */
	private Boolean newMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.reply
	 * @mbg.generated
	 */
	private Byte reply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.in_date
	 * @mbg.generated
	 */
	private Date inDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.defunct
	 * @mbg.generated
	 */
	private String defunct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.mail_id
	 * @return  the value of mail.mail_id
	 * @mbg.generated
	 */
	public Integer getMailId() {
		return mailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.mail_id
	 * @param mailId  the value for mail.mail_id
	 * @mbg.generated
	 */
	public void setMailId(Integer mailId) {
		this.mailId = mailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.to_user
	 * @return  the value of mail.to_user
	 * @mbg.generated
	 */
	public String getToUser() {
		return toUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.to_user
	 * @param toUser  the value for mail.to_user
	 * @mbg.generated
	 */
	public void setToUser(String toUser) {
		this.toUser = toUser == null ? null : toUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.from_user
	 * @return  the value of mail.from_user
	 * @mbg.generated
	 */
	public String getFromUser() {
		return fromUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.from_user
	 * @param fromUser  the value for mail.from_user
	 * @mbg.generated
	 */
	public void setFromUser(String fromUser) {
		this.fromUser = fromUser == null ? null : fromUser.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.title
	 * @return  the value of mail.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.title
	 * @param title  the value for mail.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.new_mail
	 * @return  the value of mail.new_mail
	 * @mbg.generated
	 */
	public Boolean getNewMail() {
		return newMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.new_mail
	 * @param newMail  the value for mail.new_mail
	 * @mbg.generated
	 */
	public void setNewMail(Boolean newMail) {
		this.newMail = newMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.reply
	 * @return  the value of mail.reply
	 * @mbg.generated
	 */
	public Byte getReply() {
		return reply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.reply
	 * @param reply  the value for mail.reply
	 * @mbg.generated
	 */
	public void setReply(Byte reply) {
		this.reply = reply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.in_date
	 * @return  the value of mail.in_date
	 * @mbg.generated
	 */
	public Date getInDate() {
		return inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.in_date
	 * @param inDate  the value for mail.in_date
	 * @mbg.generated
	 */
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.defunct
	 * @return  the value of mail.defunct
	 * @mbg.generated
	 */
	public String getDefunct() {
		return defunct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.defunct
	 * @param defunct  the value for mail.defunct
	 * @mbg.generated
	 */
	public void setDefunct(String defunct) {
		this.defunct = defunct == null ? null : defunct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail.content
	 * @return  the value of mail.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail.content
	 * @param content  the value for mail.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}