package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table movie
 */
public class Movie {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column movie.movie_id
	 * @mbg.generated
	 */
	private Integer movieId;
	/**
	 * Database Column Remarks: 科目 This field was generated by MyBatis Generator. This field corresponds to the database column movie.category_id
	 * @mbg.generated
	 */
	private Integer categoryId;
	/**
	 * Database Column Remarks: 标题 This field was generated by MyBatis Generator. This field corresponds to the database column movie.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * Database Column Remarks: 视频文件链接 This field was generated by MyBatis Generator. This field corresponds to the database column movie.url
	 * @mbg.generated
	 */
	private String url;
	/**
	 * Database Column Remarks: 视频描述 This field was generated by MyBatis Generator. This field corresponds to the database column movie.desc
	 * @mbg.generated
	 */
	private String desc;
	/**
	 * Database Column Remarks: 创建/编辑者id This field was generated by MyBatis Generator. This field corresponds to the database column movie.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * Database Column Remarks: 发布/修改时间 This field was generated by MyBatis Generator. This field corresponds to the database column movie.post_time
	 * @mbg.generated
	 */
	private Date postTime;
	/**
	 * Database Column Remarks: 状态：1为正常 This field was generated by MyBatis Generator. This field corresponds to the database column movie.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column movie.nice
	 * @mbg.generated
	 */
	private Integer nice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column movie.scan
	 * @mbg.generated
	 */
	private Integer scan;
	/**
	 * Database Column Remarks: 缩略图url This field was generated by MyBatis Generator. This field corresponds to the database column movie.thumb_url
	 * @mbg.generated
	 */
	private String thumbUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.movie_id
	 * @return  the value of movie.movie_id
	 * @mbg.generated
	 */
	public Integer getMovieId() {
		return movieId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.movie_id
	 * @param movieId  the value for movie.movie_id
	 * @mbg.generated
	 */
	public void setMovieId(Integer movieId) {
		this.movieId = movieId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.category_id
	 * @return  the value of movie.category_id
	 * @mbg.generated
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.category_id
	 * @param categoryId  the value for movie.category_id
	 * @mbg.generated
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.title
	 * @return  the value of movie.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.title
	 * @param title  the value for movie.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.url
	 * @return  the value of movie.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.url
	 * @param url  the value for movie.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.desc
	 * @return  the value of movie.desc
	 * @mbg.generated
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.desc
	 * @param desc  the value for movie.desc
	 * @mbg.generated
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.user_id
	 * @return  the value of movie.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.user_id
	 * @param userId  the value for movie.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.post_time
	 * @return  the value of movie.post_time
	 * @mbg.generated
	 */
	public Date getPostTime() {
		return postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.post_time
	 * @param postTime  the value for movie.post_time
	 * @mbg.generated
	 */
	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.status
	 * @return  the value of movie.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.status
	 * @param status  the value for movie.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.nice
	 * @return  the value of movie.nice
	 * @mbg.generated
	 */
	public Integer getNice() {
		return nice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.nice
	 * @param nice  the value for movie.nice
	 * @mbg.generated
	 */
	public void setNice(Integer nice) {
		this.nice = nice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.scan
	 * @return  the value of movie.scan
	 * @mbg.generated
	 */
	public Integer getScan() {
		return scan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.scan
	 * @param scan  the value for movie.scan
	 * @mbg.generated
	 */
	public void setScan(Integer scan) {
		this.scan = scan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column movie.thumb_url
	 * @return  the value of movie.thumb_url
	 * @mbg.generated
	 */
	public String getThumbUrl() {
		return thumbUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column movie.thumb_url
	 * @param thumbUrl  the value for movie.thumb_url
	 * @mbg.generated
	 */
	public void setThumbUrl(String thumbUrl) {
		this.thumbUrl = thumbUrl == null ? null : thumbUrl.trim();
	}
}