package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table news
 */
public class News {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.news_id
	 * @mbg.generated
	 */
	private Integer newsId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.importance
	 * @mbg.generated
	 */
	private Byte importance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.defunct
	 * @mbg.generated
	 */
	private String defunct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.news_id
	 * @return  the value of news.news_id
	 * @mbg.generated
	 */
	public Integer getNewsId() {
		return newsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.news_id
	 * @param newsId  the value for news.news_id
	 * @mbg.generated
	 */
	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.user_id
	 * @return  the value of news.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.user_id
	 * @param userId  the value for news.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.title
	 * @return  the value of news.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.title
	 * @param title  the value for news.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.time
	 * @return  the value of news.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.time
	 * @param time  the value for news.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.importance
	 * @return  the value of news.importance
	 * @mbg.generated
	 */
	public Byte getImportance() {
		return importance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.importance
	 * @param importance  the value for news.importance
	 * @mbg.generated
	 */
	public void setImportance(Byte importance) {
		this.importance = importance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.defunct
	 * @return  the value of news.defunct
	 * @mbg.generated
	 */
	public String getDefunct() {
		return defunct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.defunct
	 * @param defunct  the value for news.defunct
	 * @mbg.generated
	 */
	public void setDefunct(String defunct) {
		this.defunct = defunct == null ? null : defunct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news.content
	 * @return  the value of news.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news.content
	 * @param content  the value for news.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}