package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table online
 */
public class Online {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column online.hash
	 * @mbg.generated
	 */
	private String hash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column online.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column online.ua
	 * @mbg.generated
	 */
	private String ua;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column online.refer
	 * @mbg.generated
	 */
	private String refer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column online.lastmove
	 * @mbg.generated
	 */
	private Integer lastmove;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column online.firsttime
	 * @mbg.generated
	 */
	private Integer firsttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column online.uri
	 * @mbg.generated
	 */
	private String uri;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column online.hash
	 * @return  the value of online.hash
	 * @mbg.generated
	 */
	public String getHash() {
		return hash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column online.hash
	 * @param hash  the value for online.hash
	 * @mbg.generated
	 */
	public void setHash(String hash) {
		this.hash = hash == null ? null : hash.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column online.ip
	 * @return  the value of online.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column online.ip
	 * @param ip  the value for online.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column online.ua
	 * @return  the value of online.ua
	 * @mbg.generated
	 */
	public String getUa() {
		return ua;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column online.ua
	 * @param ua  the value for online.ua
	 * @mbg.generated
	 */
	public void setUa(String ua) {
		this.ua = ua == null ? null : ua.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column online.refer
	 * @return  the value of online.refer
	 * @mbg.generated
	 */
	public String getRefer() {
		return refer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column online.refer
	 * @param refer  the value for online.refer
	 * @mbg.generated
	 */
	public void setRefer(String refer) {
		this.refer = refer == null ? null : refer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column online.lastmove
	 * @return  the value of online.lastmove
	 * @mbg.generated
	 */
	public Integer getLastmove() {
		return lastmove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column online.lastmove
	 * @param lastmove  the value for online.lastmove
	 * @mbg.generated
	 */
	public void setLastmove(Integer lastmove) {
		this.lastmove = lastmove;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column online.firsttime
	 * @return  the value of online.firsttime
	 * @mbg.generated
	 */
	public Integer getFirsttime() {
		return firsttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column online.firsttime
	 * @param firsttime  the value for online.firsttime
	 * @mbg.generated
	 */
	public void setFirsttime(Integer firsttime) {
		this.firsttime = firsttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column online.uri
	 * @return  the value of online.uri
	 * @mbg.generated
	 */
	public String getUri() {
		return uri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column online.uri
	 * @param uri  the value for online.uri
	 * @mbg.generated
	 */
	public void setUri(String uri) {
		this.uri = uri == null ? null : uri.trim();
	}
}