package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table topic
 */
public class Opic {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.tid
	 * @mbg.generated
	 */
	private Integer tid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.top_level
	 * @mbg.generated
	 */
	private Integer topLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.cid
	 * @mbg.generated
	 */
	private Integer cid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.pid
	 * @mbg.generated
	 */
	private Integer pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.author_id
	 * @mbg.generated
	 */
	private String authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column topic.title
	 * @mbg.generated
	 */
	private byte[] title;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.tid
	 * @return  the value of topic.tid
	 * @mbg.generated
	 */
	public Integer getTid() {
		return tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.tid
	 * @param tid  the value for topic.tid
	 * @mbg.generated
	 */
	public void setTid(Integer tid) {
		this.tid = tid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.status
	 * @return  the value of topic.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.status
	 * @param status  the value for topic.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.top_level
	 * @return  the value of topic.top_level
	 * @mbg.generated
	 */
	public Integer getTopLevel() {
		return topLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.top_level
	 * @param topLevel  the value for topic.top_level
	 * @mbg.generated
	 */
	public void setTopLevel(Integer topLevel) {
		this.topLevel = topLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.cid
	 * @return  the value of topic.cid
	 * @mbg.generated
	 */
	public Integer getCid() {
		return cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.cid
	 * @param cid  the value for topic.cid
	 * @mbg.generated
	 */
	public void setCid(Integer cid) {
		this.cid = cid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.pid
	 * @return  the value of topic.pid
	 * @mbg.generated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.pid
	 * @param pid  the value for topic.pid
	 * @mbg.generated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.author_id
	 * @return  the value of topic.author_id
	 * @mbg.generated
	 */
	public String getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.author_id
	 * @param authorId  the value for topic.author_id
	 * @mbg.generated
	 */
	public void setAuthorId(String authorId) {
		this.authorId = authorId == null ? null : authorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column topic.title
	 * @return  the value of topic.title
	 * @mbg.generated
	 */
	public byte[] getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column topic.title
	 * @param title  the value for topic.title
	 * @mbg.generated
	 */
	public void setTitle(byte[] title) {
		this.title = title;
	}
}