package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table printer
 */
public class Printer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column printer.printer_id
	 * @mbg.generated
	 */
	private Integer printerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column printer.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column printer.in_date
	 * @mbg.generated
	 */
	private Date inDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column printer.status
	 * @mbg.generated
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column printer.worktime
	 * @mbg.generated
	 */
	private Date worktime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column printer.printer
	 * @mbg.generated
	 */
	private String printer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column printer.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column printer.printer_id
	 * @return  the value of printer.printer_id
	 * @mbg.generated
	 */
	public Integer getPrinterId() {
		return printerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column printer.printer_id
	 * @param printerId  the value for printer.printer_id
	 * @mbg.generated
	 */
	public void setPrinterId(Integer printerId) {
		this.printerId = printerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column printer.user_id
	 * @return  the value of printer.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column printer.user_id
	 * @param userId  the value for printer.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column printer.in_date
	 * @return  the value of printer.in_date
	 * @mbg.generated
	 */
	public Date getInDate() {
		return inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column printer.in_date
	 * @param inDate  the value for printer.in_date
	 * @mbg.generated
	 */
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column printer.status
	 * @return  the value of printer.status
	 * @mbg.generated
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column printer.status
	 * @param status  the value for printer.status
	 * @mbg.generated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column printer.worktime
	 * @return  the value of printer.worktime
	 * @mbg.generated
	 */
	public Date getWorktime() {
		return worktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column printer.worktime
	 * @param worktime  the value for printer.worktime
	 * @mbg.generated
	 */
	public void setWorktime(Date worktime) {
		this.worktime = worktime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column printer.printer
	 * @return  the value of printer.printer
	 * @mbg.generated
	 */
	public String getPrinter() {
		return printer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column printer.printer
	 * @param printer  the value for printer.printer
	 * @mbg.generated
	 */
	public void setPrinter(String printer) {
		this.printer = printer == null ? null : printer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column printer.content
	 * @return  the value of printer.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column printer.content
	 * @param content  the value for printer.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}