package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table privilege
 */
public class Privilege {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.rightstr
	 * @mbg.generated
	 */
	private String rightstr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column privilege.defunct
	 * @mbg.generated
	 */
	private String defunct;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.user_id
	 * @return  the value of privilege.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.user_id
	 * @param userId  the value for privilege.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.rightstr
	 * @return  the value of privilege.rightstr
	 * @mbg.generated
	 */
	public String getRightstr() {
		return rightstr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.rightstr
	 * @param rightstr  the value for privilege.rightstr
	 * @mbg.generated
	 */
	public void setRightstr(String rightstr) {
		this.rightstr = rightstr == null ? null : rightstr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column privilege.defunct
	 * @return  the value of privilege.defunct
	 * @mbg.generated
	 */
	public String getDefunct() {
		return defunct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column privilege.defunct
	 * @param defunct  the value for privilege.defunct
	 * @mbg.generated
	 */
	public void setDefunct(String defunct) {
		this.defunct = defunct == null ? null : defunct.trim();
	}
}