package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table problem
 */
public class Problem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.problem_id
	 * @mbg.generated
	 */
	private Integer problemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.spj
	 * @mbg.generated
	 */
	private String spj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.source
	 * @mbg.generated
	 */
	private String source;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.difficulty
	 * @mbg.generated
	 */
	private String difficulty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.in_date
	 * @mbg.generated
	 */
	private Date inDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.time_limit
	 * @mbg.generated
	 */
	private Integer timeLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.memory_limit
	 * @mbg.generated
	 */
	private Integer memoryLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.vip
	 * @mbg.generated
	 */
	private Integer vip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.defunct
	 * @mbg.generated
	 */
	private String defunct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.accepted
	 * @mbg.generated
	 */
	private Integer accepted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.submit
	 * @mbg.generated
	 */
	private Integer submit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.solved
	 * @mbg.generated
	 */
	private Integer solved;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.input
	 * @mbg.generated
	 */
	private String input;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.output
	 * @mbg.generated
	 */
	private String output;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.sample_input
	 * @mbg.generated
	 */
	private String sampleInput;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.sample_output
	 * @mbg.generated
	 */
	private String sampleOutput;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column problem.hint
	 * @mbg.generated
	 */
	private String hint;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.problem_id
	 * @return  the value of problem.problem_id
	 * @mbg.generated
	 */
	public Integer getProblemId() {
		return problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.problem_id
	 * @param problemId  the value for problem.problem_id
	 * @mbg.generated
	 */
	public void setProblemId(Integer problemId) {
		this.problemId = problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.title
	 * @return  the value of problem.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.title
	 * @param title  the value for problem.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.spj
	 * @return  the value of problem.spj
	 * @mbg.generated
	 */
	public String getSpj() {
		return spj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.spj
	 * @param spj  the value for problem.spj
	 * @mbg.generated
	 */
	public void setSpj(String spj) {
		this.spj = spj == null ? null : spj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.source
	 * @return  the value of problem.source
	 * @mbg.generated
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.source
	 * @param source  the value for problem.source
	 * @mbg.generated
	 */
	public void setSource(String source) {
		this.source = source == null ? null : source.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.difficulty
	 * @return  the value of problem.difficulty
	 * @mbg.generated
	 */
	public String getDifficulty() {
		return difficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.difficulty
	 * @param difficulty  the value for problem.difficulty
	 * @mbg.generated
	 */
	public void setDifficulty(String difficulty) {
		this.difficulty = difficulty == null ? null : difficulty.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.in_date
	 * @return  the value of problem.in_date
	 * @mbg.generated
	 */
	public Date getInDate() {
		return inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.in_date
	 * @param inDate  the value for problem.in_date
	 * @mbg.generated
	 */
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.time_limit
	 * @return  the value of problem.time_limit
	 * @mbg.generated
	 */
	public Integer getTimeLimit() {
		return timeLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.time_limit
	 * @param timeLimit  the value for problem.time_limit
	 * @mbg.generated
	 */
	public void setTimeLimit(Integer timeLimit) {
		this.timeLimit = timeLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.memory_limit
	 * @return  the value of problem.memory_limit
	 * @mbg.generated
	 */
	public Integer getMemoryLimit() {
		return memoryLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.memory_limit
	 * @param memoryLimit  the value for problem.memory_limit
	 * @mbg.generated
	 */
	public void setMemoryLimit(Integer memoryLimit) {
		this.memoryLimit = memoryLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.vip
	 * @return  the value of problem.vip
	 * @mbg.generated
	 */
	public Integer getVip() {
		return vip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.vip
	 * @param vip  the value for problem.vip
	 * @mbg.generated
	 */
	public void setVip(Integer vip) {
		this.vip = vip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.defunct
	 * @return  the value of problem.defunct
	 * @mbg.generated
	 */
	public String getDefunct() {
		return defunct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.defunct
	 * @param defunct  the value for problem.defunct
	 * @mbg.generated
	 */
	public void setDefunct(String defunct) {
		this.defunct = defunct == null ? null : defunct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.accepted
	 * @return  the value of problem.accepted
	 * @mbg.generated
	 */
	public Integer getAccepted() {
		return accepted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.accepted
	 * @param accepted  the value for problem.accepted
	 * @mbg.generated
	 */
	public void setAccepted(Integer accepted) {
		this.accepted = accepted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.submit
	 * @return  the value of problem.submit
	 * @mbg.generated
	 */
	public Integer getSubmit() {
		return submit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.submit
	 * @param submit  the value for problem.submit
	 * @mbg.generated
	 */
	public void setSubmit(Integer submit) {
		this.submit = submit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.solved
	 * @return  the value of problem.solved
	 * @mbg.generated
	 */
	public Integer getSolved() {
		return solved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.solved
	 * @param solved  the value for problem.solved
	 * @mbg.generated
	 */
	public void setSolved(Integer solved) {
		this.solved = solved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.description
	 * @return  the value of problem.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.description
	 * @param description  the value for problem.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.input
	 * @return  the value of problem.input
	 * @mbg.generated
	 */
	public String getInput() {
		return input;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.input
	 * @param input  the value for problem.input
	 * @mbg.generated
	 */
	public void setInput(String input) {
		this.input = input == null ? null : input.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.output
	 * @return  the value of problem.output
	 * @mbg.generated
	 */
	public String getOutput() {
		return output;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.output
	 * @param output  the value for problem.output
	 * @mbg.generated
	 */
	public void setOutput(String output) {
		this.output = output == null ? null : output.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.sample_input
	 * @return  the value of problem.sample_input
	 * @mbg.generated
	 */
	public String getSampleInput() {
		return sampleInput;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.sample_input
	 * @param sampleInput  the value for problem.sample_input
	 * @mbg.generated
	 */
	public void setSampleInput(String sampleInput) {
		this.sampleInput = sampleInput == null ? null : sampleInput.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.sample_output
	 * @return  the value of problem.sample_output
	 * @mbg.generated
	 */
	public String getSampleOutput() {
		return sampleOutput;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.sample_output
	 * @param sampleOutput  the value for problem.sample_output
	 * @mbg.generated
	 */
	public void setSampleOutput(String sampleOutput) {
		this.sampleOutput = sampleOutput == null ? null : sampleOutput.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column problem.hint
	 * @return  the value of problem.hint
	 * @mbg.generated
	 */
	public String getHint() {
		return hint;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column problem.hint
	 * @param hint  the value for problem.hint
	 * @mbg.generated
	 */
	public void setHint(String hint) {
		this.hint = hint == null ? null : hint.trim();
	}
}