package cn.liuxingwei.judge.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reply
 */
public class Reply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.rid
	 * @mbg.generated
	 */
	private Integer rid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.author_id
	 * @mbg.generated
	 */
	private String authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.topic_id
	 * @mbg.generated
	 */
	private Integer topicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.status
	 * @mbg.generated
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column reply.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.rid
	 * @return  the value of reply.rid
	 * @mbg.generated
	 */
	public Integer getRid() {
		return rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.rid
	 * @param rid  the value for reply.rid
	 * @mbg.generated
	 */
	public void setRid(Integer rid) {
		this.rid = rid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.author_id
	 * @return  the value of reply.author_id
	 * @mbg.generated
	 */
	public String getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.author_id
	 * @param authorId  the value for reply.author_id
	 * @mbg.generated
	 */
	public void setAuthorId(String authorId) {
		this.authorId = authorId == null ? null : authorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.time
	 * @return  the value of reply.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.time
	 * @param time  the value for reply.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.topic_id
	 * @return  the value of reply.topic_id
	 * @mbg.generated
	 */
	public Integer getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.topic_id
	 * @param topicId  the value for reply.topic_id
	 * @mbg.generated
	 */
	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.status
	 * @return  the value of reply.status
	 * @mbg.generated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.status
	 * @param status  the value for reply.status
	 * @mbg.generated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.ip
	 * @return  the value of reply.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.ip
	 * @param ip  the value for reply.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column reply.content
	 * @return  the value of reply.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column reply.content
	 * @param content  the value for reply.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}