package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sim
 */
public class Sim {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sim.s_id
	 * @mbg.generated
	 */
	private Integer sId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sim.sim_s_id
	 * @mbg.generated
	 */
	private Integer simSId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sim.sim
	 * @mbg.generated
	 */
	private Integer sim;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sim.s_id
	 * @return  the value of sim.s_id
	 * @mbg.generated
	 */
	public Integer getsId() {
		return sId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sim.s_id
	 * @param sId  the value for sim.s_id
	 * @mbg.generated
	 */
	public void setsId(Integer sId) {
		this.sId = sId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sim.sim_s_id
	 * @return  the value of sim.sim_s_id
	 * @mbg.generated
	 */
	public Integer getSimSId() {
		return simSId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sim.sim_s_id
	 * @param simSId  the value for sim.sim_s_id
	 * @mbg.generated
	 */
	public void setSimSId(Integer simSId) {
		this.simSId = simSId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sim.sim
	 * @return  the value of sim.sim
	 * @mbg.generated
	 */
	public Integer getSim() {
		return sim;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sim.sim
	 * @param sim  the value for sim.sim
	 * @mbg.generated
	 */
	public void setSim(Integer sim) {
		this.sim = sim;
	}
}