package cn.liuxingwei.judge.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table solution
 */
public class Solution {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.solution_id
	 * @mbg.generated
	 */
	private Integer solutionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.problem_id
	 * @mbg.generated
	 */
	private Integer problemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.user_id
	 * @mbg.generated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.time
	 * @mbg.generated
	 */
	private Integer time;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.memory
	 * @mbg.generated
	 */
	private Integer memory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.in_date
	 * @mbg.generated
	 */
	private Date inDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.result
	 * @mbg.generated
	 */
	private Short result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.language
	 * @mbg.generated
	 */
	private Integer language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.contest_id
	 * @mbg.generated
	 */
	private Integer contestId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.valid
	 * @mbg.generated
	 */
	private Byte valid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.num
	 * @mbg.generated
	 */
	private Byte num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.code_length
	 * @mbg.generated
	 */
	private Integer codeLength;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.judgetime
	 * @mbg.generated
	 */
	private Date judgetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.pass_rate
	 * @mbg.generated
	 */
	private BigDecimal passRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.lint_error
	 * @mbg.generated
	 */
	private Integer lintError;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column solution.judger
	 * @mbg.generated
	 */
	private String judger;
	/**
	 * Database Column Remarks: 过期状态，为1为正常情况下提交的成绩，为2则是已结束情况下提交的成绩 This field was generated by MyBatis Generator. This field corresponds to the database column solution.is_expire
	 * @mbg.generated
	 */
	private Byte isExpire;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.solution_id
	 * @return  the value of solution.solution_id
	 * @mbg.generated
	 */
	public Integer getSolutionId() {
		return solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.solution_id
	 * @param solutionId  the value for solution.solution_id
	 * @mbg.generated
	 */
	public void setSolutionId(Integer solutionId) {
		this.solutionId = solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.problem_id
	 * @return  the value of solution.problem_id
	 * @mbg.generated
	 */
	public Integer getProblemId() {
		return problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.problem_id
	 * @param problemId  the value for solution.problem_id
	 * @mbg.generated
	 */
	public void setProblemId(Integer problemId) {
		this.problemId = problemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.user_id
	 * @return  the value of solution.user_id
	 * @mbg.generated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.user_id
	 * @param userId  the value for solution.user_id
	 * @mbg.generated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.time
	 * @return  the value of solution.time
	 * @mbg.generated
	 */
	public Integer getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.time
	 * @param time  the value for solution.time
	 * @mbg.generated
	 */
	public void setTime(Integer time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.memory
	 * @return  the value of solution.memory
	 * @mbg.generated
	 */
	public Integer getMemory() {
		return memory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.memory
	 * @param memory  the value for solution.memory
	 * @mbg.generated
	 */
	public void setMemory(Integer memory) {
		this.memory = memory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.in_date
	 * @return  the value of solution.in_date
	 * @mbg.generated
	 */
	public Date getInDate() {
		return inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.in_date
	 * @param inDate  the value for solution.in_date
	 * @mbg.generated
	 */
	public void setInDate(Date inDate) {
		this.inDate = inDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.result
	 * @return  the value of solution.result
	 * @mbg.generated
	 */
	public Short getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.result
	 * @param result  the value for solution.result
	 * @mbg.generated
	 */
	public void setResult(Short result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.language
	 * @return  the value of solution.language
	 * @mbg.generated
	 */
	public Integer getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.language
	 * @param language  the value for solution.language
	 * @mbg.generated
	 */
	public void setLanguage(Integer language) {
		this.language = language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.ip
	 * @return  the value of solution.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.ip
	 * @param ip  the value for solution.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.contest_id
	 * @return  the value of solution.contest_id
	 * @mbg.generated
	 */
	public Integer getContestId() {
		return contestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.contest_id
	 * @param contestId  the value for solution.contest_id
	 * @mbg.generated
	 */
	public void setContestId(Integer contestId) {
		this.contestId = contestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.valid
	 * @return  the value of solution.valid
	 * @mbg.generated
	 */
	public Byte getValid() {
		return valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.valid
	 * @param valid  the value for solution.valid
	 * @mbg.generated
	 */
	public void setValid(Byte valid) {
		this.valid = valid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.num
	 * @return  the value of solution.num
	 * @mbg.generated
	 */
	public Byte getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.num
	 * @param num  the value for solution.num
	 * @mbg.generated
	 */
	public void setNum(Byte num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.code_length
	 * @return  the value of solution.code_length
	 * @mbg.generated
	 */
	public Integer getCodeLength() {
		return codeLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.code_length
	 * @param codeLength  the value for solution.code_length
	 * @mbg.generated
	 */
	public void setCodeLength(Integer codeLength) {
		this.codeLength = codeLength;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.judgetime
	 * @return  the value of solution.judgetime
	 * @mbg.generated
	 */
	public Date getJudgetime() {
		return judgetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.judgetime
	 * @param judgetime  the value for solution.judgetime
	 * @mbg.generated
	 */
	public void setJudgetime(Date judgetime) {
		this.judgetime = judgetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.pass_rate
	 * @return  the value of solution.pass_rate
	 * @mbg.generated
	 */
	public BigDecimal getPassRate() {
		return passRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.pass_rate
	 * @param passRate  the value for solution.pass_rate
	 * @mbg.generated
	 */
	public void setPassRate(BigDecimal passRate) {
		this.passRate = passRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.lint_error
	 * @return  the value of solution.lint_error
	 * @mbg.generated
	 */
	public Integer getLintError() {
		return lintError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.lint_error
	 * @param lintError  the value for solution.lint_error
	 * @mbg.generated
	 */
	public void setLintError(Integer lintError) {
		this.lintError = lintError;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.judger
	 * @return  the value of solution.judger
	 * @mbg.generated
	 */
	public String getJudger() {
		return judger;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.judger
	 * @param judger  the value for solution.judger
	 * @mbg.generated
	 */
	public void setJudger(String judger) {
		this.judger = judger == null ? null : judger.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column solution.is_expire
	 * @return  the value of solution.is_expire
	 * @mbg.generated
	 */
	public Byte getIsExpire() {
		return isExpire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column solution.is_expire
	 * @param isExpire  the value for solution.is_expire
	 * @mbg.generated
	 */
	public void setIsExpire(Byte isExpire) {
		this.isExpire = isExpire;
	}
}