package cn.liuxingwei.judge.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table source_code
 */
public class Sourcecode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column source_code.solution_id
	 * @mbg.generated
	 */
	private Integer solutionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column source_code.source
	 * @mbg.generated
	 */
	private String source;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column source_code.solution_id
	 * @return  the value of source_code.solution_id
	 * @mbg.generated
	 */
	public Integer getSolutionId() {
		return solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column source_code.solution_id
	 * @param solutionId  the value for source_code.solution_id
	 * @mbg.generated
	 */
	public void setSolutionId(Integer solutionId) {
		this.solutionId = solutionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column source_code.source
	 * @return  the value of source_code.source
	 * @mbg.generated
	 */
	public String getSource() {
		return source;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column source_code.source
	 * @param source  the value for source_code.source
	 * @mbg.generated
	 */
	public void setSource(String source) {
		this.source = source == null ? null : source.trim();
	}
}