package cn.liuxingwei.judge.domain;

import lombok.Data;
import org.springframework.stereotype.Component;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users
 */
@Component
@Data
public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_exp
     *
     * @mbg.generated
     */
    private Integer userExp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.submit
     *
     * @mbg.generated
     */
    private Integer submit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.solved
     *
     * @mbg.generated
     */
    private Integer solved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.blog_cnt
     *
     * @mbg.generated
     */
    private Integer blogCnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.defunct
     *
     * @mbg.generated
     */
    private String defunct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.accesstime
     *
     * @mbg.generated
     */
    private Date accesstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.volume
     *
     * @mbg.generated
     */
    private Integer volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.language
     *
     * @mbg.generated
     */
    private Integer language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reg_time
     *
     * @mbg.generated
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nick
     *
     * @mbg.generated
     */
    private String nick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_id
     *
     * @return the value of users.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_exp
     *
     * @return the value of users.user_exp
     *
     * @mbg.generated
     */
    public Integer getUserExp() {
        return userExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_exp
     *
     * @param userExp the value for users.user_exp
     *
     * @mbg.generated
     */
    public void setUserExp(Integer userExp) {
        this.userExp = userExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.submit
     *
     * @return the value of users.submit
     *
     * @mbg.generated
     */
    public Integer getSubmit() {
        return submit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.submit
     *
     * @param submit the value for users.submit
     *
     * @mbg.generated
     */
    public void setSubmit(Integer submit) {
        this.submit = submit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.solved
     *
     * @return the value of users.solved
     *
     * @mbg.generated
     */
    public Integer getSolved() {
        return solved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.solved
     *
     * @param solved the value for users.solved
     *
     * @mbg.generated
     */
    public void setSolved(Integer solved) {
        this.solved = solved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.blog_cnt
     *
     * @return the value of users.blog_cnt
     *
     * @mbg.generated
     */
    public Integer getBlogCnt() {
        return blogCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.blog_cnt
     *
     * @param blogCnt the value for users.blog_cnt
     *
     * @mbg.generated
     */
    public void setBlogCnt(Integer blogCnt) {
        this.blogCnt = blogCnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.defunct
     *
     * @return the value of users.defunct
     *
     * @mbg.generated
     */
    public String getDefunct() {
        return defunct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.defunct
     *
     * @param defunct the value for users.defunct
     *
     * @mbg.generated
     */
    public void setDefunct(String defunct) {
        this.defunct = defunct == null ? null : defunct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ip
     *
     * @return the value of users.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ip
     *
     * @param ip the value for users.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.accesstime
     *
     * @return the value of users.accesstime
     *
     * @mbg.generated
     */
    public Date getAccesstime() {
        return accesstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.accesstime
     *
     * @param accesstime the value for users.accesstime
     *
     * @mbg.generated
     */
    public void setAccesstime(Date accesstime) {
        this.accesstime = accesstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.volume
     *
     * @return the value of users.volume
     *
     * @mbg.generated
     */
    public Integer getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.volume
     *
     * @param volume the value for users.volume
     *
     * @mbg.generated
     */
    public void setVolume(Integer volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.language
     *
     * @return the value of users.language
     *
     * @mbg.generated
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.language
     *
     * @param language the value for users.language
     *
     * @mbg.generated
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reg_time
     *
     * @return the value of users.reg_time
     *
     * @mbg.generated
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reg_time
     *
     * @param regTime the value for users.reg_time
     *
     * @mbg.generated
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nick
     *
     * @return the value of users.nick
     *
     * @mbg.generated
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nick
     *
     * @param nick the value for users.nick
     *
     * @mbg.generated
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.school
     *
     * @return the value of users.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.school
     *
     * @param school the value for users.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sign
     *
     * @return the value of users.sign
     *
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sign
     *
     * @param sign the value for users.sign
     *
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }
}