package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Article;
import java.util.List;

public interface ArticleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated
	 */
	int insert(Article record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated
	 */
	Article selectByPrimaryKey(Integer articleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated
	 */
	List<Article> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table article
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Article record);
}