package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Balloon;
import java.util.List;

public interface BalloonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balloon
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer balloonId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balloon
	 * @mbg.generated
	 */
	int insert(Balloon record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balloon
	 * @mbg.generated
	 */
	Balloon selectByPrimaryKey(Integer balloonId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balloon
	 * @mbg.generated
	 */
	List<Balloon> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table balloon
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Balloon record);
}