package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Blogdiscuss;
import java.util.List;

public interface BlogdiscussMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog_discuss
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer discussId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog_discuss
	 * @mbg.generated
	 */
	int insert(Blogdiscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog_discuss
	 * @mbg.generated
	 */
	Blogdiscuss selectByPrimaryKey(Integer discussId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog_discuss
	 * @mbg.generated
	 */
	List<Blogdiscuss> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog_discuss
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Blogdiscuss record);
}