package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Choicequestion;
import java.util.List;

public interface ChoicequestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice_question
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer choiceQuestionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice_question
	 * @mbg.generated
	 */
	int insert(Choicequestion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice_question
	 * @mbg.generated
	 */
	Choicequestion selectByPrimaryKey(Integer choiceQuestionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice_question
	 * @mbg.generated
	 */
	List<Choicequestion> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table choice_question
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Choicequestion record);
}