package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Contestproblem;
import java.util.List;

public interface ContestproblemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contest_problem
	 * @mbg.generated
	 */
	int insert(Contestproblem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contest_problem
	 * @mbg.generated
	 */
	List<Contestproblem> selectAll();
}