package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Contest;
import java.util.List;

public interface ContestMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contest
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer contestId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contest
	 * @mbg.generated
	 */
	int insert(Contest record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contest
	 * @mbg.generated
	 */
	Contest selectByPrimaryKey(Integer contestId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contest
	 * @mbg.generated
	 */
	List<Contest> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table contest
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Contest record);
}