package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Dbinfoinc;
import java.util.List;

public interface DbinfoincMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db_info_inc
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String varKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db_info_inc
	 * @mbg.generated
	 */
	int insert(Dbinfoinc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db_info_inc
	 * @mbg.generated
	 */
	Dbinfoinc selectByPrimaryKey(String varKey);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db_info_inc
	 * @mbg.generated
	 */
	List<Dbinfoinc> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table db_info_inc
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Dbinfoinc record);
}