package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Exam;
import java.util.List;

public interface ExamMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer examId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbg.generated
	 */
	int insert(Exam record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbg.generated
	 */
	Exam selectByPrimaryKey(Integer examId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbg.generated
	 */
	List<Exam> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table exam
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Exam record);
}