package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Loginlog;
import java.util.List;

public interface LoginlogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loginlog
	 * @mbg.generated
	 */
	int insert(Loginlog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table loginlog
	 * @mbg.generated
	 */
	List<Loginlog> selectAll();
}