package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Mail;
import java.util.List;

public interface MailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer mailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail
	 * @mbg.generated
	 */
	int insert(Mail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail
	 * @mbg.generated
	 */
	Mail selectByPrimaryKey(Integer mailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail
	 * @mbg.generated
	 */
	List<Mail> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Mail record);
}