package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Movie;
import java.util.List;

public interface MovieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table movie
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer movieId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table movie
	 * @mbg.generated
	 */
	int insert(Movie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table movie
	 * @mbg.generated
	 */
	Movie selectByPrimaryKey(Integer movieId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table movie
	 * @mbg.generated
	 */
	List<Movie> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table movie
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Movie record);
}