package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Online;
import java.util.List;

public interface OnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table online
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String hash);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table online
	 * @mbg.generated
	 */
	int insert(Online record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table online
	 * @mbg.generated
	 */
	Online selectByPrimaryKey(String hash);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table online
	 * @mbg.generated
	 */
	List<Online> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table online
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Online record);
}