package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Pdf;
import java.util.List;

public interface PdfMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer pdfId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf
	 * @mbg.generated
	 */
	int insert(Pdf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf
	 * @mbg.generated
	 */
	Pdf selectByPrimaryKey(Integer pdfId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf
	 * @mbg.generated
	 */
	List<Pdf> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdf
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Pdf record);
}