package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Printer;
import java.util.List;

public interface PrinterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table printer
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer printerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table printer
	 * @mbg.generated
	 */
	int insert(Printer record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table printer
	 * @mbg.generated
	 */
	Printer selectByPrimaryKey(Integer printerId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table printer
	 * @mbg.generated
	 */
	List<Printer> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table printer
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Printer record);
}