package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Privilege;
import java.util.List;

public interface PrivilegeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbg.generated
	 */
	int insert(Privilege record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table privilege
	 * @mbg.generated
	 */
	List<Privilege> selectAll();
}