package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Question;
import java.util.List;

public interface QuestionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer questionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbg.generated
	 */
	int insert(Question record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbg.generated
	 */
	Question selectByPrimaryKey(Integer questionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbg.generated
	 */
	List<Question> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table question
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Question record);
}