package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Reply;
import java.util.List;

public interface ReplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer rid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated
	 */
	int insert(Reply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated
	 */
	Reply selectByPrimaryKey(Integer rid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated
	 */
	List<Reply> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table reply
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Reply record);
}