package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Runtimeinfo;
import java.util.List;

public interface RuntimeinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table runtimeinfo
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table runtimeinfo
	 * @mbg.generated
	 */
	int insert(Runtimeinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table runtimeinfo
	 * @mbg.generated
	 */
	Runtimeinfo selectByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table runtimeinfo
	 * @mbg.generated
	 */
	List<Runtimeinfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table runtimeinfo
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Runtimeinfo record);
}