package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Sim;
import java.util.List;

public interface SimMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sim
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer sId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sim
	 * @mbg.generated
	 */
	int insert(Sim record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sim
	 * @mbg.generated
	 */
	Sim selectByPrimaryKey(Integer sId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sim
	 * @mbg.generated
	 */
	List<Sim> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sim
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Sim record);
}