package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Solution;
import java.util.List;

public interface SolutionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solution
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solution
	 * @mbg.generated
	 */
	int insert(Solution record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solution
	 * @mbg.generated
	 */
	Solution selectByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solution
	 * @mbg.generated
	 */
	List<Solution> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table solution
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Solution record);
}