package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Sourcecodeuser;
import java.util.List;

public interface SourcecodeuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code_user
	 * @mbg.generated
	 */
	int insert(Sourcecodeuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code_user
	 * @mbg.generated
	 */
	Sourcecodeuser selectByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code_user
	 * @mbg.generated
	 */
	List<Sourcecodeuser> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Sourcecodeuser record);
}