package cn.liuxingwei.judge.mapper;

import cn.liuxingwei.judge.domain.Sourcecode;
import java.util.List;

public interface SourcecodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code
	 * @mbg.generated
	 */
	int insert(Sourcecode record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code
	 * @mbg.generated
	 */
	Sourcecode selectByPrimaryKey(Integer solutionId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code
	 * @mbg.generated
	 */
	List<Sourcecode> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table source_code
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Sourcecode record);
}